// src/components/community/Sessions.vue
<script setup lang="ts">
// Sessions de bmx : rendez-vous proposés par les membres (spot ou ville),
// avec inscription en un clic.

import { onMounted, ref } from 'vue'
import { api, ApiError, type BMXSession } from '../../api'
import { useAuth } from '../../auth'
import { useI18n, type Lang } from '../../i18n'
import Avatar from '../Avatar.vue'

const DATE_LOCALES: Record<Lang, string> = {
  fr: 'fr-FR',
  en: 'en-GB',
  es: 'es-ES',
  de: 'de-DE',
  pt: 'pt-PT',
  zh: 'zh-CN',
  ja: 'ja-JP',
}

function fmtWhen(iso: string, lang: Lang): string {
  return new Date(iso).toLocaleString(DATE_LOCALES[lang], {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  })
}

const { user } = useAuth()
const { t, lang } = useI18n()
const sessions = ref<BMXSession[]>([])
const adding = ref(false)
const error = ref<string | null>(null)

onMounted(() => {
  api
    .sessions()
    .then((s) => (sessions.value = s))
    .catch((e) => (error.value = e instanceof ApiError ? e.message : t('sessions.loadError')))
})

function replace(s: BMXSession) {
  sessions.value = sessions.value.map((x) => (x.id === s.id ? s : x))
}

async function toggle(s: BMXSession, joined: boolean) {
  try {
    replace(joined ? await api.leaveSession(s.id) : await api.joinSession(s.id))
  } catch (e) {
    error.value = e instanceof ApiError ? e.message : t('sessions.error')
  }
}

function isJoined(s: BMXSession): boolean {
  return !!user.value && s.members.some((m) => m.id === user.value!.id)
}

function onCreated(s: BMXSession) {
  sessions.value = [...sessions.value, s].sort((a, b) => a.starts_at.localeCompare(b.starts_at))
  adding.value = false
}

// --- SessionForm (formulaire) ---
const fTitle = ref('')
const fCity = ref(user.value?.city ?? '')
const fWhen = ref('')
const fDescription = ref('')
const fBusy = ref(false)
const fError = ref<string | null>(null)

async function submit() {
  const date = new Date(fWhen.value)
  if (Number.isNaN(date.getTime())) return
  fBusy.value = true
  fError.value = null
  try {
    const created = await api.createSession({
      title: fTitle.value.trim(),
      city: fCity.value.trim() || undefined,
      description: fDescription.value.trim() || undefined,
      starts_at: date.toISOString(),
    })
    onCreated(created)
  } catch (e) {
    fError.value = e instanceof ApiError ? e.message : t('sessions.error')
  } finally {
    fBusy.value = false
  }
}

function openForm() {
  adding.value = !adding.value
  if (adding.value) {
    fTitle.value = ''
    fCity.value = user.value?.city ?? ''
    fWhen.value = ''
    fDescription.value = ''
    fBusy.value = false
    fError.value = null
  }
}
</script>

<template>
  <div class="sessions">
    <div class="spots__bar">
      <span class="spots__count">
        {{ t('sessions.count').replace('{n}', String(sessions.length)) }}
      </span>
      <button
        v-if="user"
        :class="`btn ${adding ? 'btn--ghost' : 'btn--accent'}`"
        @click="openForm"
      >
        {{ adding ? t('sessions.cancel') : t('sessions.add') }}
      </button>
      <span v-else class="spots__hint">{{ t('sessions.guest') }}</span>
    </div>

    <p v-if="error" class="account__error">{{ error }}</p>

    <form v-if="adding" class="spots__form" @submit.prevent="submit">
      <input class="field" :placeholder="t('sessions.form.title')" v-model="fTitle" required />
      <div class="market__offer-row">
        <input
          class="field"
          type="datetime-local"
          :aria-label="t('sessions.form.when')"
          v-model="fWhen"
          required
        />
        <input class="field" :placeholder="t('sessions.form.city')" v-model="fCity" />
      </div>
      <textarea
        class="field"
        :placeholder="t('sessions.form.description')"
        v-model="fDescription"
        :rows="2"
      />
      <p v-if="fError" class="account__error">{{ fError }}</p>
      <div class="spots__form-actions">
        <button type="button" class="btn btn--ghost" @click="adding = false">
          {{ t('sessions.cancel') }}
        </button>
        <button class="btn btn--accent" :disabled="!fTitle.trim() || !fWhen || fBusy">
          {{ t('sessions.form.send') }}
        </button>
      </div>
    </form>

    <p v-if="sessions.length === 0 && !adding" class="market__empty">{{ t('sessions.empty') }}</p>

    <ul class="sessions__list">
      <li v-for="s in sessions" :key="s.id" class="sessions__card">
        <div class="sessions__when">{{ fmtWhen(s.starts_at, lang) }}</div>
        <div class="sessions__body">
          <strong class="sessions__title">{{ s.title }}</strong>
          <span class="sessions__meta">
            {{ s.city ? `📍 ${s.city} · ` : '' }}
            {{ t('sessions.host').replace('{name}', s.host.display_name ?? s.host.username ?? '—') }}
          </span>
          <p v-if="s.description" class="sessions__desc">{{ s.description }}</p>
          <div class="sessions__riders">
            <span class="sessions__avatars">
              <Avatar
                v-for="(m, i) in s.members.slice(0, 5)"
                :key="m.id ?? i"
                :url="m.avatar_url"
                :name="m.display_name ?? '?'"
                :size="24"
                bare
              />
            </span>
            <span class="sessions__countlbl">
              {{ t('sessions.riders').replace('{n}', String(s.members_count)) }}
            </span>
            <button
              v-if="user"
              :class="`btn ${isJoined(s) ? 'btn--ghost' : 'btn--accent'}`"
              @click="toggle(s, isJoined(s))"
            >
              {{ isJoined(s) ? t('sessions.leave') : t('sessions.join') }}
            </button>
          </div>
        </div>
      </li>
    </ul>
  </div>
</template>

// src/components/community/Sessions.tsx
// Sessions de bmx : rendez-vous proposés par les membres (spot ou ville),
// avec inscription en un clic.

import { useEffect, useState } from 'react'
import { api, ApiError, type BMXSession } from '../../api'
import { useAuth } from '../../auth'
import { useI18n, type Lang } from '../../i18n'
import { Avatar } from '../Avatar'

const DATE_LOCALES: Record<Lang, string> = {
  fr: 'fr-FR',
  en: 'en-GB',
  es: 'es-ES',
  de: 'de-DE',
  pt: 'pt-PT',
  zh: 'zh-CN',
  ja: 'ja-JP',
}

function fmtWhen(iso: string, lang: Lang): string {
  return new Date(iso).toLocaleString(DATE_LOCALES[lang], {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  })
}

export function Sessions() {
  const { user } = useAuth()
  const { t, lang } = useI18n()
  const [sessions, setSessions] = useState<BMXSession[]>([])
  const [adding, setAdding] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    api
      .sessions()
      .then(setSessions)
      .catch((e) => setError(e instanceof ApiError ? e.message : t('sessions.loadError')))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function replace(s: BMXSession) {
    setSessions((prev) => prev.map((x) => (x.id === s.id ? s : x)))
  }

  async function toggle(s: BMXSession, joined: boolean) {
    try {
      replace(joined ? await api.leaveSession(s.id) : await api.joinSession(s.id))
    } catch (e) {
      setError(e instanceof ApiError ? e.message : t('sessions.error'))
    }
  }

  return (
    <div className="sessions">
      <div className="spots__bar">
        <span className="spots__count">
          {t('sessions.count').replace('{n}', String(sessions.length))}
        </span>
        {user ? (
          <button
            className={`btn ${adding ? 'btn--ghost' : 'btn--accent'}`}
            onClick={() => setAdding((a) => !a)}
          >
            {adding ? t('sessions.cancel') : t('sessions.add')}
          </button>
        ) : (
          <span className="spots__hint">{t('sessions.guest')}</span>
        )}
      </div>

      {error && <p className="account__error">{error}</p>}

      {adding && (
        <SessionForm
          onCreated={(s) => {
            setSessions((prev) =>
              [...prev, s].sort((a, b) => a.starts_at.localeCompare(b.starts_at)),
            )
            setAdding(false)
          }}
          onCancel={() => setAdding(false)}
        />
      )}

      {sessions.length === 0 && !adding && <p className="market__empty">{t('sessions.empty')}</p>}

      <ul className="sessions__list">
        {sessions.map((s) => {
          const joined = !!user && s.members.some((m) => m.id === user.id)
          return (
            <li key={s.id} className="sessions__card">
              <div className="sessions__when">{fmtWhen(s.starts_at, lang)}</div>
              <div className="sessions__body">
                <strong className="sessions__title">{s.title}</strong>
                <span className="sessions__meta">
                  {s.city ? `📍 ${s.city} · ` : ''}
                  {t('sessions.host').replace(
                    '{name}',
                    s.host.display_name ?? s.host.username ?? '—',
                  )}
                </span>
                {s.description && <p className="sessions__desc">{s.description}</p>}
                <div className="sessions__riders">
                  <span className="sessions__avatars">
                    {s.members.slice(0, 5).map((m, i) => (
                      <Avatar key={m.id ?? i} url={m.avatar_url} name={m.display_name ?? '?'} size={24} bare />
                    ))}
                  </span>
                  <span className="sessions__countlbl">
                    {t('sessions.riders').replace('{n}', String(s.members_count))}
                  </span>
                  {user && (
                    <button
                      className={`btn ${joined ? 'btn--ghost' : 'btn--accent'}`}
                      onClick={() => toggle(s, joined)}
                    >
                      {joined ? t('sessions.leave') : t('sessions.join')}
                    </button>
                  )}
                </div>
              </div>
            </li>
          )
        })}
      </ul>
    </div>
  )
}

function SessionForm({
  onCreated,
  onCancel,
}: {
  onCreated: (s: BMXSession) => void
  onCancel: () => void
}) {
  const { t } = useI18n()
  const { user } = useAuth()
  const [title, setTitle] = useState('')
  const [city, setCity] = useState(user?.city ?? '')
  const [when, setWhen] = useState('')
  const [description, setDescription] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function submit(e: React.FormEvent) {
    e.preventDefault()
    const date = new Date(when)
    if (Number.isNaN(date.getTime())) return
    setBusy(true)
    setError(null)
    try {
      const created = await api.createSession({
        title: title.trim(),
        city: city.trim() || undefined,
        description: description.trim() || undefined,
        starts_at: date.toISOString(),
      })
      onCreated(created)
    } catch (e) {
      setError(e instanceof ApiError ? e.message : t('sessions.error'))
    } finally {
      setBusy(false)
    }
  }

  return (
    <form className="spots__form" onSubmit={submit}>
      <input
        className="field"
        placeholder={t('sessions.form.title')}
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        required
      />
      <div className="market__offer-row">
        <input
          className="field"
          type="datetime-local"
          aria-label={t('sessions.form.when')}
          value={when}
          onChange={(e) => setWhen(e.target.value)}
          required
        />
        <input
          className="field"
          placeholder={t('sessions.form.city')}
          value={city}
          onChange={(e) => setCity(e.target.value)}
        />
      </div>
      <textarea
        className="field"
        placeholder={t('sessions.form.description')}
        value={description}
        onChange={(e) => setDescription(e.target.value)}
        rows={2}
      />
      {error && <p className="account__error">{error}</p>}
      <div className="spots__form-actions">
        <button type="button" className="btn btn--ghost" onClick={onCancel}>
          {t('sessions.cancel')}
        </button>
        <button className="btn btn--accent" disabled={!title.trim() || !when || busy}>
          {t('sessions.form.send')}
        </button>
      </div>
    </form>
  )
}
