// src/components/Manifesto.vue
<script setup lang="ts">
import { useReveal } from '../composables/pwa'
import { useI18n } from '../i18n'

const { el, visible } = useReveal()
const { t } = useI18n()
</script>

<template>
  <section id="manifeste" ref="el" class="manifesto reveal" :class="{ 'is-visible': visible }">
    <p class="section__kicker">{{ t('manifesto.kicker') }}</p>
    <h2 class="manifesto__text">{{ t('manifesto.text') }}</h2>
    <p class="manifesto__sign">{{ t('manifesto.sign') }}</p>
  </section>
</template>

// src/components/Manifesto.tsx
import { useReveal } from '../hooks'
import { useI18n } from '../i18n'

export function Manifesto() {
  const { ref, visible } = useReveal<HTMLElement>()
  const { t } = useI18n()

  return (
    <section
      id="manifeste"
      ref={ref}
      className={`manifesto reveal ${visible ? 'is-visible' : ''}`}
    >
      <p className="section__kicker">{t('manifesto.kicker')}</p>
      <h2 className="manifesto__text">{t('manifesto.text')}</h2>
      <p className="manifesto__sign">{t('manifesto.sign')}</p>
    </section>
  )
}
