// src/components/Tricks.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useReveal } from '../composables/pwa'
import { useI18n } from '../i18n'

const { el, visible } = useReveal()
const { t } = useI18n()
const active = ref(0)

// Noms de tricks BMX (universels, non traduits) ; le niveau et la description
// viennent du dictionnaire.
const TRICKS = ['Bunny hop', '180', 'Grind', 'Manual', 'Tailwhip']

function pad(i: number) {
  return String(i + 1).padStart(2, '0')
}
</script>

<template>
  <section id="tricks" ref="el" class="tricks reveal" :class="{ 'is-visible': visible }">
    <header class="tricks__head">
      <p class="section__kicker">{{ t('tricks.kicker') }}</p>
      <h2 class="section__title">{{ t('tricks.title') }}</h2>
    </header>

    <div class="tricks__list" role="tablist" :aria-label="t('tricks.list')">
      <button
        v-for="(name, i) in TRICKS"
        :key="name"
        role="tab"
        :aria-selected="i === active"
        class="trick"
        :class="{ 'trick--open': i === active }"
        @click="active = i"
      >
        <span class="trick__index">{{ pad(i) }}</span>
        <span class="trick__body">
          <span class="trick__name">{{ name }}</span>
          <span class="trick__level">{{ t(`tricks.${i + 1}.level`) }}</span>
          <span class="trick__text">{{ t(`tricks.${i + 1}.text`) }}</span>
        </span>
        <span class="trick__chevron" aria-hidden="true">{{ i === active ? '–' : '+' }}</span>
      </button>
    </div>
  </section>
</template>

// src/components/Tricks.tsx
import { useState } from 'react'
import { useReveal } from '../hooks'
import { useI18n } from '../i18n'

// Les noms de tricks sont des termes universels (non traduits) ; le niveau et
// la description viennent du dictionnaire.
const TRICKS = ['Ollie', 'Kickflip', 'Boardslide', 'Manual', '50-50 grind']

export function Tricks() {
  const { ref, visible } = useReveal<HTMLElement>()
  const { t } = useI18n()
  const [active, setActive] = useState(0)

  return (
    <section id="tricks" ref={ref} className={`tricks reveal ${visible ? 'is-visible' : ''}`}>
      <header className="tricks__head">
        <p className="section__kicker">{t('tricks.kicker')}</p>
        <h2 className="section__title">{t('tricks.title')}</h2>
      </header>

      <div className="tricks__list" role="tablist" aria-label={t('tricks.list')}>
        {TRICKS.map((name, i) => {
          const open = i === active
          return (
            <button
              key={name}
              role="tab"
              aria-selected={open}
              className={`trick ${open ? 'trick--open' : ''}`}
              onClick={() => setActive(i)}
            >
              <span className="trick__index">{String(i + 1).padStart(2, '0')}</span>
              <span className="trick__body">
                <span className="trick__name">{name}</span>
                <span className="trick__level">{t(`tricks.${i + 1}.level`)}</span>
                <span className="trick__text">{t(`tricks.${i + 1}.text`)}</span>
              </span>
              <span className="trick__chevron" aria-hidden="true">
                {open ? '–' : '+'}
              </span>
            </button>
          )
        })}
      </div>
    </section>
  )
}
